## IMPORTING LIBRARIES

In [83]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(
    { "figure.figsize": (6, 4) },
    style='ticks',
    color_codes=True,
    font_scale=0.8
)
%config InlineBackend.figure_format = 'retina'
import warnings
warnings.filterwarnings('ignore')

import statsmodels.api as sm

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler, FunctionTransformer
from sklearn.compose import ColumnTransformer
from category_encoders import TargetEncoder
import category_encoders as ce
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import PredictionErrorDisplay
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE, SelectKBest, f_regression
from sklearn.feature_selection import SequentialFeatureSelector

# For reproducibility
random_state = 42

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

### USING SYSTEM GPU

In [84]:
import torch

def test_pytorch_gpu():
    print("PyTorch version:", torch.__version__)
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print("CUDA is available. Using GPU.")
    else:
        device = torch.device("cpu")
        print("CUDA is not available. Using CPU.")
    
    # Tensor operation to test GPU
    x = torch.randn((2, 2), device=device)
    y = torch.randn((2, 2), device=device)
    z = x + y
    print("x + y on device:", z, "\nDevice:", z.device)
    print("Done.")

if __name__ == "__main__":
    test_pytorch_gpu()

PyTorch version: 2.6.0+cu118
CUDA is available. Using GPU.
x + y on device: tensor([[ 3.4511,  0.5422],
        [-2.1022,  1.0669]], device='cuda:0')
Device: cuda:0
Done.

In [85]:
car_auto = pd.read_csv('adverts.csv')

##  1. Data Description and Pre-Processing

In [86]:
car_auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402005 entries, 0 to 402004
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   public_reference       402005 non-null  int64
 1   mileage                401878 non-null  float64
 2   reg_code               370148 non-null  object
 3   standard_colour        396627 non-null  object
 4   standard_make          402005 non-null  object
 5   standard_model         402005 non-null  object
 6   vehicle_condition      402005 non-null  object
 7   year_of_registration   368694 non-null  float64
 8   price                  402005 non-null  int64
 9   body_type              401168 non-null  object
 10  crossover_car_and_van  402005 non-null  bool
 11  fuel_type              401404 non-null  object
dtypes: bool(1), float64(2), int64(2), object(7)
memory usage: 34.1+ MB

In [87]:
car_auto.head(7)

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type
0,202006039777689,0.0,NaN,Grey,Volvo,XC90,NEW,NaN,73970,SUV,False,Petrol Plug-in Hybrid
1,202007020778260,108230.0,61,Blue,Jaguar,XF,USED,2011.0,7000,Saloon,False,Diesel
2,202007020778474,7800.0,17,Grey,SKODA,Yeti,USED,2017.0,14000,SUV,False,Petrol
3,202007080986776,45000.0,16,Brown,Vauxhall,Mokka,USED,2016.0,7995,Hatchback,False,Diesel
4,202007161321269,64000.0,64,Grey,Land Rover,Range Rover Sport,USED,2015.0,26995,SUV,False,Diesel
5,202009304412074,16000.0,17,Blue,Audi,S5,USED,2017.0,29000,Convertible,False,Petrol
6,202007080998445,24075.0,17,Red,Vauxhall,Viva,USED,2017.0,5861,Hatchback,False,Petrol

In [88]:
car_auto.describe(include='all')

,public_reference,mileage,reg_code,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type
count,4.020050e+05,401878.000000,370148,396627,402005,402005,402005,368694.000000,4.020050e+05,401168,402005,401404
unique,NaN,NaN,72,22,110,1168,2,NaN,NaN,16,2,9
top,NaN,NaN,17,Black,BMW,Golf,USED,NaN,NaN,Hatchback,False,Petrol
freq,NaN,NaN,36738,86287,37376,11583,370756,NaN,NaN,167315,400210,216929
mean,2.020071e+14,37743.595656,NaN,NaN,NaN,NaN,NaN,2015.006206,1.734197e+04,NaN,NaN,NaN
std,1.691662e+10,34831.724018,NaN,NaN,NaN,NaN,NaN,7.962667,4.643746e+04,NaN,NaN,NaN
min,2.013072e+14,0.000000,NaN,NaN,NaN,NaN,NaN,999.000000,1.200000e+02,NaN,NaN,NaN
25%,2.020090e+14,10481.000000,NaN,NaN,NaN,NaN,NaN,2013.000000,7.495000e+03,NaN,NaN,NaN
50%,2.020093e+14,28629.500000,NaN,NaN,NaN,NaN,NaN,2016.000000,1.260000e+04,NaN,NaN,NaN
75%,2.020102e+14,56875.750000,NaN,NaN,NaN,NaN,NaN,2018.000000,2.000000e+04,NaN,NaN,NaN
max,2.020110e+14,999999.000000,NaN,NaN,NaN,NaN,NaN,2020.000000,9.999999e+06,NaN,NaN,NaN

In [89]:
car_auto.isna().sum()

public_reference             0
mileage                    127
reg_code                 31857
standard_colour           5378
standard_make                0
standard_model               0
vehicle_condition            0
year_of_registration     33311
price                        0
body_type                  837
crossover_car_and_van        0
fuel_type                  601
dtype: int64

### 1.2 PREPROCESSING PIPELINE

Creating a pipeline to identify and handle missing values, outliers, noise; encode categorical variables; scale features; partition data into training, validation and test sets.

1. Cap Outliers (Mileage) with quantile-based boundaries.

2. Impute Mileage by (standard_make, vehicle_condition) group median.

3. Fix Year

 For rows with year_of_registration < 1933, fill from reg_code group median.

If vehicle_condition == 'NEW' and missing, set to 2021.

Otherwise, brand-based median fallback, then global median.

4. Parse public_reference into (year_listed, month_listed, day_listed).

5. Impute Standard Colour by (standard_make, vehicle_condition) mode.

6. Impute Body Type & Fuel Type by standard_make mode.

7. Map categories in body_type, fuel_type, and standard_colour to consolidated groups.

8. Drop reg_code (after it’s been used in the year fix).

In [90]:


# ─────────────────────────────────────────────────────────────────
# A) CapOutliers
# ─────────────────────────────────────────────────────────────────
class CapOutliers(BaseEstimator, TransformerMixin):
    """
    Caps outliers in a specified numeric column based on quantiles.
    """
    def __init__(self, column, lower_quantile=0.05, upper_quantile=0.95, factor=1.5):
        self.column = column
        self.lower_quantile = lower_quantile
        self.upper_quantile = upper_quantile
        self.factor = factor
        self.lower_bound_ = None
        self.upper_bound_ = None

    def fit(self, X, y=None):
        Q1 = X[self.column].quantile(self.lower_quantile)
        Q3 = X[self.column].quantile(self.upper_quantile)
        IQR = Q3 - Q1
        self.lower_bound_ = Q1 - self.factor * IQR
        self.upper_bound_ = Q3 + self.factor * IQR
        return self

    def transform(self, X):
        X = X.copy()
        X[self.column] = X[self.column].clip(lower=self.lower_bound_, upper=self.upper_bound_)
        return X

# ─────────────────────────────────────────────────────────────────
# B) GroupMedianImputerMileage
# ─────────────────────────────────────────────────────────────────
class GroupMedianImputerMileage(BaseEstimator, TransformerMixin):
    """
    Replace missing values in 'mileage' with the median mileage grouped by
    ('standard_make', 'vehicle_condition'). Then fallback to global median.
    """
    def __init__(self):
        self.group_medians_ = None
        self.global_median_ = None

    def fit(self, X, y=None):
        X_temp = X.copy()
        self.group_medians_ = X_temp.groupby(
            ['standard_make', 'vehicle_condition']
        )['mileage'].median()
        self.global_median_ = X_temp['mileage'].median()
        return self

    def transform(self, X):
        X = X.copy()

        def fill_mileage(row):
            if pd.isna(row['mileage']):
                return self.group_medians_.get(
                    (row['standard_make'], row['vehicle_condition']),
                    self.global_median_  # fallback
                )
            return row['mileage']

        X['mileage'] = X.apply(fill_mileage, axis=1)
        return X

# ─────────────────────────────────────────────────────────────────
# C) YearRegistrationFixer
#    Uses 'reg_code' for out-of-range years, then drops 'reg_code' later
# ─────────────────────────────────────────────────────────────────
class YearRegistrationFixer(BaseEstimator, TransformerMixin):
    """
    - For year_of_registration < 1933 => fill from reg_code median if available
    - If vehicle_condition == NEW and missing => 2021
    - Else fill missing with brand-based median => global fallback
    """
    def __init__(self):
        self.regcode_medians_ = None
        self.brand_medians_ = None
        self.global_median_ = None

    def fit(self, X, y=None):
        X_temp = X.copy()

        # 1) regcode-based median for out-of-range
        if 'reg_code' in X_temp.columns:
            self.regcode_medians_ = X_temp.groupby('reg_code')['year_of_registration'].median()

        # 2) brand-based median for missing
        self.brand_medians_ = X_temp.groupby('standard_make')['year_of_registration'].median()
        self.global_median_ = X_temp['year_of_registration'].median()

        return self

    def transform(self, X):
        X = X.copy()

        def fix_out_of_range(row):
            y = row['year_of_registration']
            if pd.notna(y) and y < 1933:
                # Use regcode median if available
                if self.regcode_medians_ is not None:
                    return self.regcode_medians_.get(row['reg_code'], y)
            return y

        X['year_of_registration'] = X.apply(fix_out_of_range, axis=1)

        # Next: vehicle_condition == NEW & missing => 2021
        mask_new_and_nan = (X['vehicle_condition'] == 'NEW') & (X['year_of_registration'].isnull())
        X.loc[mask_new_and_nan, 'year_of_registration'] = 2021

        # Then fill remaining missing with brand median => fallback global
        def fill_brand_median(row):
            y = row['year_of_registration']
            if pd.isna(y):
                return self.brand_medians_.get(row['standard_make'], np.nan)
            return y

        X['year_of_registration'] = X.apply(fill_brand_median, axis=1)
        X['year_of_registration'] = X['year_of_registration'].fillna(self.global_median_)

        # Convert to int
        X['year_of_registration'] = X['year_of_registration'].astype(int, errors='ignore')

        return X

# ─────────────────────────────────────────────────────────────────
# D) ParsePublicReference
# ─────────────────────────────────────────────────────────────────
class ParsePublicReference(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        X['public_reference'] = X['public_reference'].astype(str)

        X['year_listed'] = X['public_reference'].str[:4].astype(int)
        X['month_listed'] = X['public_reference'].str[4:6].astype(int)
        X['day_listed'] = X['public_reference'].str[6:8].astype(int)

        # We'll drop public_reference in a separate step if we want
        return X

# ─────────────────────────────────────────────────────────────────
# E) StandardColourImputer
# ─────────────────────────────────────────────────────────────────
class StandardColourImputer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()

        def impute_with_mode(group):
            mode_val = group['standard_colour'].mode()
            if not mode_val.empty:
                return group['standard_colour'].fillna(mode_val[0])
            else:
                return group['standard_colour'].fillna('Unknown')

        # Group by (make, condition) for color
        X['standard_colour'] = (
            X.groupby(['standard_make', 'vehicle_condition'], group_keys=False)
             .apply(impute_with_mode)
        )
        # Final fallback
        X['standard_colour'] = X['standard_colour'].fillna('Unknown')
        return X

# ─────────────────────────────────────────────────────────────────
# F) BodyFuelImputer
# ─────────────────────────────────────────────────────────────────
class BodyFuelImputer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()

        # Body type by standard_make
        def fill_body_mode(group):
            mode_val = group['body_type'].mode()
            return group['body_type'].fillna(mode_val[0] if not mode_val.empty else 'unknown')

        X['body_type'] = (
            X.groupby('standard_make', group_keys=False)
             .apply(fill_body_mode)
        )

        # Fuel type by standard_make
        def fill_fuel_mode(group):
            mode_val = group['fuel_type'].mode()
            return group['fuel_type'].fillna(mode_val[0] if not mode_val.empty else 'Unknown')

        X['fuel_type'] = (
            X.groupby('standard_make', group_keys=False)
             .apply(fill_fuel_mode)
        )

        return X

# ─────────────────────────────────────────────────────────────────
# G) MapBodyTypeFuelColour
# ─────────────────────────────────────────────────────────────────
class MapBodyTypeFuelColour(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.body_type_mapping = {
            'Hatchback': 'Hatchback',
            'SUV': 'SUV',
            'Saloon': 'Saloon',
            'Estate': 'Estate',
            'Coupe': 'Coupe',
            'Convertible': 'Convertible',
            'MPV': 'MPV',
            'Pickup': 'Utility Vehicles',
            'Combi Van': 'Utility Vehicles',
            'Panel Van': 'Utility Vehicles',
            'Window Van': 'Utility Vehicles',
            'Camper': 'Utility Vehicles',
            'Limousine': 'Luxury/Passenger Vehicles',
            'Minibus': 'Luxury/Passenger Vehicles',
            'Chassis Cab': 'Utility Vehicles',
            'Car Derived Van': 'Utility Vehicles',
            'unknown': 'Utility Vehicles'
        }

        self.fuel_type_mapping = {
            'Petrol': 'Petrol',
            'Diesel': 'Diesel',
            'Electric': 'Electric',
            'Petrol Hybrid': 'Hybrid',
            'Diesel Hybrid': 'Hybrid',
            'Petrol Plug-in Hybrid': 'Hybrid',
            'Diesel Plug-in Hybrid': 'Hybrid',
            'Natural Gas': 'Bi/Gas',
            'Bi Fuel': 'Bi/Gas'
        }

        self.color_mapping = {
            'Bronze': 'Metallic',
            'Gold': 'Metallic',
            'Beige': 'Metallic',
            'Pink': 'Red/Purple',
            'Purple': 'Red/Purple',
            'Magenta': 'Red/Purple',
            'Burgundy': 'Red/Purple',
            'Multicolour': 'Custom',
            'Turquoise': 'Custom',
            'Yellow': 'Yellow',
            'Brown': 'Brown',
            'Navy': 'Blue',
            'Maroon': 'Red/Purple',
            'Unknown': 'Unknown',
            'Indigo': 'Blue'
        }

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()

        # Body types
        X['body_type'] = X['body_type'].map(self.body_type_mapping).fillna('Utility Vehicles')

        # Fuel
        X['fuel_type'] = X['fuel_type'].map(self.fuel_type_mapping).fillna('Unknown')

        # Colour
        X['standard_colour'] = X['standard_colour'].replace(self.color_mapping)

        return X

# ─────────────────────────────────────────────────────────────────
# H) DropColumns
#    We'll drop 'public_reference' and 'reg_code' (the latter after it's used)
# ─────────────────────────────────────────────────────────────────
class DropColumns(BaseEstimator, TransformerMixin):
    def __init__(self, cols_to_drop):
        self.cols_to_drop = cols_to_drop

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()
        X.drop(columns=self.cols_to_drop, inplace=True, errors='ignore')
        return X

In [91]:
def create_cleaning_pipeline():
    """
    Creates a pipeline that:
      1) Caps outliers in 'mileage'
      2) Imputes 'mileage' by (make, condition) median
      3) Fixes 'year_of_registration' using reg_code for <1933, then brand-based median
      4) Parses 'public_reference' => year_listed, month_listed, day_listed
      5) Imputes standard_colour by (make, condition) mode
      6) Imputes body_type, fuel_type by make mode
      7) Maps categories for body_type, fuel_type, standard_colour
      8) Drops 'reg_code' and 'public_reference'
    """
    return Pipeline([
        ("cap_outliers", CapOutliers(column="mileage", lower_quantile=0.05, upper_quantile=0.95)),
        ("impute_mileage", GroupMedianImputerMileage()),
        ("fix_year", YearRegistrationFixer()),
        ("parse_pubref", ParsePublicReference()),
        ("impute_colour", StandardColourImputer()),
        ("impute_bodyfuel", BodyFuelImputer()),
        ("map_bfc", MapBodyTypeFuelColour()),
        # Finally drop columns we don't need in the final dataset:
        ("drop_unused", DropColumns(cols_to_drop=["reg_code", "public_reference"]))
    ])

In [92]:
# Implementing the pipeline
pipeline = create_cleaning_pipeline()

# Fit-transform
car_auto_cl = pipeline.fit_transform(car_auto)

print("Shape after cleaning:", car_auto_cl.shape)
print(car_auto_cl.info())
car_auto_cl.head(10)

Shape after cleaning: (402005, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 402005 entries, 0 to 402004
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   mileage                402005 non-null  float64
 1   standard_colour        402005 non-null  object
 2   standard_make          402005 non-null  object
 3   standard_model         402005 non-null  object
 4   vehicle_condition      402005 non-null  object
 5   year_of_registration   402005 non-null  int64
 6   price                  402005 non-null  int64
 7   body_type              402005 non-null  object
 8   crossover_car_and_van  402005 non-null  bool
 9   fuel_type              402005 non-null  object
 10  year_listed            402005 non-null  int64
 11  month_listed           402005 non-null  int64
 12  day_listed             402005 non-null  int64
dtypes: bool(1), float64(1), int64(5), object(6)
memory usage: 37.2+ MB
None

,mileage,standard_colour,standard_make,standard_model,vehicle_condition,year_of_registration,price,body_type,crossover_car_and_van,fuel_type,year_listed,month_listed,day_listed
0,0.0,Grey,Volvo,XC90,NEW,2021,73970,SUV,False,Hybrid,2020,6,3
1,108230.0,Blue,Jaguar,XF,USED,2011,7000,Saloon,False,Diesel,2020,7,2
2,7800.0,Grey,SKODA,Yeti,USED,2017,14000,SUV,False,Petrol,2020,7,2
3,45000.0,Brown,Vauxhall,Mokka,USED,2016,7995,Hatchback,False,Diesel,2020,7,8
4,64000.0,Grey,Land Rover,Range Rover Sport,USED,2015,26995,SUV,False,Diesel,2020,7,16
5,16000.0,Blue,Audi,S5,USED,2017,29000,Convertible,False,Petrol,2020,9,30
6,24075.0,Red,Vauxhall,Viva,USED,2017,5861,Hatchback,False,Petrol,2020,7,8
7,99000.0,Metallic,Land Rover,Range Rover,USED,2013,24475,SUV,False,Diesel,2020,9,24
8,111236.0,Black,Mercedes-Benz,S Class,USED,2008,6995,Luxury/Passenger Vehicles,False,Diesel,2020,10,1
9,9500.0,White,Land Rover,Range Rover,USED,2019,79995,SUV,False,Diesel,2020,6,23

#### Saving the file

In [93]:
car_auto_cl.to_csv('adverts_cl.csv', index=False)

### Secondary Pipeline for feature engineering and transformation

multi-step workflow that creates additional features, handles categorical encodings (including target encoding for high-cardinality columns), applies log transforms, and then partitions the data into train/validation/test sets without data leakage

In [97]:

# --- Custom Transformer for Label Encoding 'vehicle_condition'
class VehicleConditionLabelEncoder(BaseEstimator, TransformerMixin):
    """Encodes 'vehicle_condition' using LabelEncoder."""
    def __init__(self):
        self.le_ = LabelEncoder()
    
    def fit(self, X, y=None):
        self.le_.fit(X['vehicle_condition'].astype(str))
        return self
    
    def transform(self, X):
        X = X.copy()
        X['vehicle_condition'] = self.le_.transform(X['vehicle_condition'].astype(str))
        return X

# --- Feature Engineering Transformer
class FeatureEngineer(BaseEstimator, TransformerMixin):
    """
    Creates meaningful features from raw car data:
    - vehicle_age = year_listed - year_of_registration (clipped to a minimum of 0)
    - mileage_per_year = mileage / (vehicle_age + epsilon)
    - mileage_age_interaction = mileage * vehicle_age
    - listing_month_day = month_listed * 100 + day_listed
    - standard_make_model = standard_make + "_" + standard_model
    - is_luxury_brand = binary indicator for luxury brands
    Then drops raw string/date columns no longer needed.
    """
    def __init__(self, luxury_brands=None, drop_vehicle_age=False):
        # Ensure the luxury brands list is all lowercase.
        self.luxury_brands = luxury_brands or [
            'mercedes-benz', 'bmw', 'audi', 'lexus', 'porsche', 
            'jaguar', 'land rover', 'bentley', 'maserati', 'ferrari', 'lamborghini'
        ]
        self.drop_vehicle_age = drop_vehicle_age
        
    def fit(self, X, y=None):
        self.input_columns_ = X.columns.tolist()
        return self
        
    def transform(self, X):
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X, columns=self.input_columns_)
        X = X.copy()
        
        # 1) Vehicle age computation.
        X['vehicle_age'] = X['year_listed'] - X['year_of_registration']
        X['vehicle_age'] = X['vehicle_age'].clip(lower=0)
        
        # 2) Mileage per year.
        X['mileage_per_year'] = X['mileage'] / (X['vehicle_age'] + 0.001)
        
        # 3) Mileage-age interaction.
        X['mileage_age_interaction'] = X['mileage'] * X['vehicle_age']
        
        # 4) Listing month_day.
        X['listing_month_day'] = X['month_listed'] * 100 + X['day_listed']
        
        # 5) Standard make_model.
        X['standard_make_model'] = X['standard_make'] + "_" + X['standard_model']
        
        # 6) Luxury brand indicator.
        X['is_luxury_brand'] = X['standard_make'].str.lower().isin(self.luxury_brands).astype(int)
        
        # Optionally drop 'vehicle_age'
        if self.drop_vehicle_age:
            X = X.drop(columns=['vehicle_age'], errors='ignore')
            
        # Drop raw columns not needed further.
        cols_to_drop = ['standard_make', 'standard_model', 'year_listed', 'month_listed', 'day_listed']
        X = X.drop(columns=cols_to_drop, errors='ignore')
        
        return X

# --- Simple Target Encoder for High-Cardinality Features
class SimpleTargetEncoder(BaseEstimator, TransformerMixin):
    """
    Target encoder for high-cardinality categorical features.
    Uses the mean target value per category with smoothing.
    """
    def __init__(self, cols=None, smoothing=10.0, min_samples_leaf=1):
        self.cols = cols if cols is not None else []
        self.smoothing = smoothing
        self.min_samples_leaf = min_samples_leaf
        self.mapping = {}
        self.global_mean = None
        
    def fit(self, X, y):
        X_temp = X.copy()
        self.global_mean = y.mean()
        for col in self.cols:
            if col not in X_temp.columns:
                continue
            stats = pd.DataFrame({
                'sum': y.groupby(X_temp[col]).sum(),
                'count': y.groupby(X_temp[col]).count()
            })
            stats['mean'] = (stats['sum'] + self.smoothing * self.global_mean) / (stats['count'] + self.smoothing)
            self.mapping[col] = stats['mean'].to_dict()
        return self
        
    def transform(self, X):
        X_temp = X.copy()
        for col in self.cols:
            if col not in X_temp.columns:
                continue
            X_temp[col] = X_temp[col].map(self.mapping.get(col, {})).fillna(self.global_mean)
        return X_temp

# --- Boolean to Int Converter
class BooleanToInt(BaseEstimator, TransformerMixin):
    """Converts boolean columns to integers (0/1)."""
    def __init__(self, cols=None):
        self.cols = cols if cols is not None else []
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        for col in self.cols:
            if col in X.columns:
                X[col] = X[col].astype(int)
        return X

# --- Log Transformer
class LogTransformer(BaseEstimator, TransformerMixin):
    """
    Applies log1p transform to specified numeric columns.
    """
    def __init__(self, cols=None):
        self.cols = cols if cols is not None else []
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        X = X.copy()
        for col in self.cols:
            if col in X.columns:
                X[col] = np.log1p(X[col].clip(lower=0))
        return X

# --- Custom DataFrame One-Hot Encoder
class DataFrameOneHotEncoder(BaseEstimator, TransformerMixin):
    """
    Wraps OneHotEncoder and returns a DataFrame with appropriate column names.
    Only transforms specified columns and concatenates with the remaining columns.
    """
    def __init__(self, ohe_columns, drop='first'):
        self.ohe_columns = ohe_columns
        self.drop = drop
        self.ohe_ = OneHotEncoder(drop=self.drop, sparse_output=False, handle_unknown='ignore')
        self.feature_names_ = None
    
    def fit(self, X, y=None):
        # Fit OneHotEncoder on the specified columns.
        self.ohe_.fit(X[self.ohe_columns])
        # Get new feature names.
        self.feature_names_ = self.ohe_.get_feature_names_out(self.ohe_columns)
        return self
    
    def transform(self, X):
        X = X.copy()
        # Transform the specified columns using OneHotEncoder.
        ohe_array = self.ohe_.transform(X[self.ohe_columns])
        df_ohe = pd.DataFrame(ohe_array, columns=self.feature_names_, index=X.index)
        # Drop the original ohe_columns from X.
        X = X.drop(columns=self.ohe_columns, errors='ignore')
        # Concatenate one-hot encoded columns with the remaining columns.
        return pd.concat([df_ohe, X], axis=1)

# --- Custom Scaler that Preserves Column Names
class ScalerWithNames(StandardScaler):
    def fit(self, X, y=None):
        # Store column names.
        self.feature_names_in_ = X.columns.tolist()
        return super().fit(X, y)
    
    def transform(self, X, y=None):
        X_scaled = super().transform(X, y)
        return pd.DataFrame(X_scaled, columns=self.feature_names_in_, index=X.index)

# --- Advanced Pipeline Builder (Revised Order with Name Preservation)
def create_advanced_pipeline(
    ohe_cols=None,
    log_cols=None,
    target_encode_cols=None,
    bool_cols=None,
    luxury_brands=None,
    do_scaling=False
):
    """
    Creates an advanced pipeline that returns a DataFrame with column names.
    
    Steps:
      1) Feature engineering.
      2) Boolean-to-integer conversion.
      3) Target encoding for high-cardinality features.
      4) Label encoding for 'vehicle_condition'.
      5) Log transformation for specified numeric columns.
      6) One-hot encoding for selected low-card categorical columns (DataFrame output).
      7) (Optional) Standard scaling (preserving names).
    """
    # Set defaults.
    if ohe_cols is None:
        ohe_cols = ["fuel_type", "body_type", "standard_colour"]
    if log_cols is None:
        log_cols = ["mileage", "mileage_age_interaction", "mileage_per_year"]
    if target_encode_cols is None:
        target_encode_cols = ["standard_make_model"]
    if bool_cols is None:
        bool_cols = ["crossover_car_and_van"]
    
    # 1) Feature engineering.
    feature_step = ("feature_engineer", FeatureEngineer(
        luxury_brands=luxury_brands,
        drop_vehicle_age=False
    ))
    
    # 2) Boolean-to-int conversion.
    bool_step = ("bool_to_int", BooleanToInt(cols=bool_cols))
    
    # 3) Target encoding for high-cardinality columns.
    target_encoder_step = ("target_encoder", SimpleTargetEncoder(
        cols=target_encode_cols,
        smoothing=10.0
    ))
    
    # 4) Label encoding for 'vehicle_condition'.
    label_encoder_step = ("vehicle_condition_le", VehicleConditionLabelEncoder())
    
    # 5) Log transformation.
    log_step = ("log_transform", LogTransformer(cols=log_cols))
    
    # 6) One-hot encoding using custom DataFrameOneHotEncoder.
    one_hot_step = ("one_hot_encoder", DataFrameOneHotEncoder(ohe_columns=ohe_cols, drop='first'))
    
    # Assemble pipeline steps.
    steps = [
        feature_step,
        bool_step,
        target_encoder_step,
        label_encoder_step,
        log_step,
        one_hot_step
    ]
    
    # 7) Optional scaling with column names.
    if do_scaling:
        steps.append(("scaler", ScalerWithNames()))
    
    pipeline = Pipeline(steps)
    return pipeline

# --- Data Split Function
def prepare_data_splits(df, target_col='price', test_size=0.2, val_size=0.25, random_state=42):
    """
    Splits the data into training, validation, and test sets.
    """
    y = df[target_col]
    X = df.drop(columns=[target_col])
    X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=val_size, random_state=random_state)
    print(f"Training set: {X_train.shape[0]} samples")
    print(f"Validation set: {X_val.shape[0]} samples")
    print(f"Test set: {X_test.shape[0]} samples")
    return X_train, X_val, X_test, y_train, y_val, y_test

# --- Example Usage
if __name__ == "__main__":
    # Assume 'car_auto_cl' is your pre-cleaned DataFrame with target 'price'.
    car_auto_fin = car_auto_cl.copy()
    
    # Define parameters.
    ohe_cols = ["fuel_type", "body_type", "standard_colour"]
    log_cols = ["mileage", "mileage_age_interaction", "mileage_per_year"]
    target_encode_cols = ["standard_make_model"]
    bool_cols = ["crossover_car_and_van"]
    luxury_brands = [
        'mercedes-benz', 'bmw', 'audi', 'lexus', 'porsche', 
        'jaguar', 'land rover', 'bentley', 'maserati', 'ferrari', 'lamborghini'
    ]
    
    # Create train/validation/test splits.
    X_train, X_val, X_test, y_train, y_val, y_test = prepare_data_splits(car_auto_fin, target_col='price')
    
    # Build pipeline. Set do_scaling=True for linear/polynomial models, False for tree-based.
    advanced_pipeline = create_advanced_pipeline(
        ohe_cols=ohe_cols,
        log_cols=log_cols,
        target_encode_cols=target_encode_cols,
        bool_cols=bool_cols,
        luxury_brands=luxury_brands,
        do_scaling=False  # change to True if needed
    )
    
    # Fit the pipeline on training data (y_train is used for target encoding).
    advanced_pipeline.fit(X_train, y_train)
    
    # Transform train, validation, and test sets.
    X_train_final = advanced_pipeline.transform(X_train)
    X_val_final = advanced_pipeline.transform(X_val)
    X_test_final = advanced_pipeline.transform(X_test)
    
    print("Training final shape:", X_train_final.shape)
    print("Validation final shape:", X_val_final.shape)
    print("Test final shape:", X_test_final.shape)

Training set: 241203 samples
Validation set: 80401 samples
Test set: 80401 samples
Training final shape: (241203, 35)
Validation final shape: (80401, 35)
Test final shape: (80401, 35)

In [98]:
X_train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 241203 entries, 284701 to 157493
Data columns (total 35 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   fuel_type_Diesel                     241203 non-null  float64
 1   fuel_type_Electric                   241203 non-null  float64
 2   fuel_type_Hybrid                     241203 non-null  float64
 3   fuel_type_Petrol                     241203 non-null  float64
 4   body_type_Coupe                      241203 non-null  float64
 5   body_type_Estate                     241203 non-null  float64
 6   body_type_Hatchback                  241203 non-null  float64
 7   body_type_Luxury/Passenger Vehicles  241203 non-null  float64
 8   body_type_MPV                        241203 non-null  float64
 9   body_type_SUV                        241203 non-null  float64
 10  body_type_Saloon                     241203 non-null  float64
 11  body_type_Utility Vehicles           241203 non-null  float64
 12  standard_colour_Blue                 241203 non-null  float64
 13  standard_colour_Brown                241203 non-null  float64
 14  standard_colour_Custom               241203 non-null  float64
 15  standard_colour_Green                241203 non-null  float64
 16  standard_colour_Grey                 241203 non-null  float64
 17  standard_colour_Metallic             241203 non-null  float64
 18  standard_colour_Orange               241203 non-null  float64
 19  standard_colour_Red                  241203 non-null  float64
 20  standard_colour_Red/Purple           241203 non-null  float64
 21  standard_colour_Silver               241203 non-null  float64
 22  standard_colour_Unknown              241203 non-null  float64
 23  standard_colour_White                241203 non-null  float64
 24  standard_colour_Yellow               241203 non-null  float64
 25  mileage                              241203 non-null  float64
 26  vehicle_condition                    241203 non-null  int64
 27  year_of_registration                 241203 non-null  int64
 28  crossover_car_and_van                241203 non-null  int64
 29  vehicle_age                          241203 non-null  int64
 30  mileage_per_year                     241203 non-null  float64
 31  mileage_age_interaction              241203 non-null  float64
 32  listing_month_day                    241203 non-null  int64
 33  standard_make_model                  241203 non-null  float64
 34  is_luxury_brand                      241203 non-null  int64
dtypes: float64(29), int64(6)
memory usage: 66.2 MB

## 2. Automated Feature Selection

1. RFE vs. From-Model vs. SFS:

RFE:

Pros: Relatively easy to set up, uses the model’s estimates to recursively reduce features.

Cons: Can be computationally expensive if you remove one feature at a time; may be unstable if the model is sensitive to data splits.

From-Model Feature Importance:

Pros: Requires training just one model (or a few) and is very fast.

Cons: Importance is model-specific; results may differ significantly depending on the estimator chosen.

Sequential Feature Selection (SFS):

Pros: Provides a systematic search (either forward or backward), can be tuned with cross-validation.

Cons: Computationally expensive and may get stuck in local minima, since it’s a greedy algorithm.

### RFE (RECURSIVE FEATURE ELIMINATION)

RFE so far is computationally slow

In [ ]:
def run_rfe(X, y, n_features_to_select=10, estimator=None):
    """
    Runs Recursive Feature Elimination (RFE) with cross-validation.
    
    Parameters:
      X (DataFrame): Training features.
      y (Series): Target variable.
      n_features_to_select (int): Number of features to select.
      estimator: A scikit-learn estimator supporting feature importance. 
                 Defaults to RandomForestRegressor.
    
    Returns:
      selected_features: Index (or list) of features selected.
      rfe: The fitted RFE selector (for additional inspection).
      cv_scores: Cross-validation score (e.g. mean RMSE) of estimator on selected features.
    """
    if estimator is None:
        estimator = RandomForestRegressor(random_state=random_state)
    
    # Create RFE selector.
    rfe_selector = RFE(estimator=estimator, n_features_to_select=n_features_to_select, step=3)
    rfe_selector.fit(X, y)
    
    # Get the mask or feature list.
    selected_mask = rfe_selector.support_
    selected_features = X.columns[selected_mask]
    
    # Evaluate via cross-validation on selected features:
    cv = KFold(n_splits=3, shuffle=True, random_state=random_state)
    scores = cross_val_score(estimator, X[selected_features], y, scoring='neg_mean_squared_error', cv=cv)
    rmse_scores = np.sqrt(-scores)
    
    print("RFE selected features:")
    print(selected_features.tolist())
    print("RFE CV RMSE: Mean = {:.2f}, Std = {:.2f}".format(rmse_scores.mean(), rmse_scores.std()))
    
    return selected_features, rfe_selector, rmse_scores

# Usage:
rfe_features, rfe_selector, rfe_scores = run_rfe(X_train_final, y_train, n_features_to_select=10)